### ISSUE TITLE
Bug: Cannot remove wallet from list until connection is successfully added

### ISSUE THREAD

**Issue by matjaz** [getAlby/go#205] opened 2024-12-04 17:27 UTC
I can not remove a new wallet from list, until connection is successfully added.

**Comment by rolznz** [comment] 2024-12-06 06:49
First part is a duplicate of https://github.com/getAlby/go/issues/172

I will update this issue for the second point, thanks for reporting!

**Comment by im-adithya** [comment] 2024-12-24 06:09
This issue is resolved in v1.7, you can now delete wallets without being redirected to set those up

Issue: https://github.com/getAlby/go/issues/164
PR: https://github.com/getAlby/go/pull/143

**Closed by im-adithya** 2024-12-24 06:09 UTC
